apiVersion: v1
kind: Secret
metadata:
  name: rks-shared-secrets
  namespace: rks-logistics
type: Opaque
stringData:
  DATABASE_URL: "postgresql://<db_user>:<db_password>@<db_host>:6543/postgres"
  JWT_SECRET: change_this_secret
  OPENROUTESERVICE_API_KEY: ""
