apiVersion: v1
kind: Secret
metadata:
  name: rks-shared-secrets
  namespace: rks-logistics
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: tesco123
  POSTGRES_DB: rks
  DATABASE_URL: "postgresql://postgres:tesco123@postgres:7519/rks"
  JWT_SECRET: "rks_jwt_2026_prod_x8N7s4Qm2L9vR1tK6pD3yH5c"
