apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: rks-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: rks-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3200
          envFrom:
            - configMapRef:
                name: rks-shared-config
            - secretRef:
                name: rks-shared-secrets
          env:
            - name: PORT
              value: "3200"
