apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: rks-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: rks-auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3201
          envFrom:
            - configMapRef:
                name: rks-shared-config
            - secretRef:
                name: rks-shared-secrets
          env:
            - name: PORT
              value: "3201"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rks-shared-secrets
                  key: DATABASE_URL
