apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleet-service
  namespace: rks-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleet-service
  template:
    metadata:
      labels:
        app: fleet-service
    spec:
      containers:
        - name: fleet-service
          image: docker.io/harisankarsundaram/rks-fleet-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3202
          envFrom:
            - configMapRef:
                name: rks-shared-config
            - secretRef:
                name: rks-shared-secrets
          env:
            - name: PORT
              value: "3202"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rks-shared-secrets
                  key: DATABASE_URL
