apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  namespace: rks-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-service
  template:
    metadata:
      labels:
        app: ml-service
    spec:
      containers:
        - name: ml-service
          image: docker.io/harisankarsundaram/rks-ml-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
