apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimization-service
  namespace: rks-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimization-service
  template:
    metadata:
      labels:
        app: optimization-service
    spec:
      containers:
        - name: optimization-service
          image: docker.io/harisankarsundaram/rks-optimization-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3209
          envFrom:
            - configMapRef:
                name: rks-shared-config
            - secretRef:
                name: rks-shared-secrets
          env:
            - name: PORT
              value: "3209"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: rks-shared-secrets
                  key: DATABASE_URL
