apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: rks-logistics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          imagePullPolicy: IfNotPresent
          args:
            - "-p"
            - "7519"
          ports:
            - containerPort: 7519
          envFrom:
            - configMapRef:
                name: rks-shared-config
            - secretRef:
                name: rks-shared-secrets
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
