apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: rks-logistics
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: 3200
      protocol: TCP
  type: ClusterIP
