apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: rks-logistics
spec:
  selector:
    app: booking-service
  ports:
    - port: 3204
      targetPort: 3204
      protocol: TCP
  type: ClusterIP
