apiVersion: v1
kind: Service
metadata:
  name: fleet-service
  namespace: rks-logistics
spec:
  selector:
    app: fleet-service
  ports:
    - port: 3202
      targetPort: 3202
      protocol: TCP
  type: ClusterIP
