apiVersion: v1
kind: Service
metadata:
  name: mock-gps-service
  namespace: rks-logistics
spec:
  selector:
    app: mock-gps-service
  ports:
    - port: 3206
      targetPort: 3206
      protocol: TCP
  type: ClusterIP
