apiVersion: v1
kind: Service
metadata:
  name: optimization-service
  namespace: rks-logistics
spec:
  selector:
    app: optimization-service
  ports:
    - port: 3209
      targetPort: 3209
      protocol: TCP
  type: ClusterIP
