apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: rks-logistics
spec:
  selector:
    app: postgres
  ports:
    - port: 7519
      targetPort: 7519
      protocol: TCP
  type: ClusterIP
